export enum actionTypes {
  CATEGORIES_FETCH_REQUEST = "CATEGORIES_FETCH_REQUEST",
  CATEGORIES_FETCH_SUCCESS = "CATEGORIES_FETCH_SUCCESS",
  CATEGORIES_FETCH_FAILURE = "CATEGORIES_FETCH_FAILURE",

  BOARD_FETCH_REQUEST = "BOARD_FETCH_REQUEST",
  BOARD_FETCH_SUCCESS = "BOARD_FETCH_SUCCESS",
  BOARD_FETCH_FAILURE = "BOARD_FETCH_FAILURE",

  THREADS_FETCH_REQUEST = "THREADS_FETCH_REQUEST",
  THREADS_FETCH_SUCCESS = "THREADS_FETCH_SUCCESS",
  THREADS_FETCH_FAILURE = "THREADS_FETCH_FAILURE",

  SINGLE_THREAD_FETCH_REQUEST = "SINGLE_THREAD_FETCH_REQUEST",
  SINGLE_THREAD_FETCH_SUCCESS = "SINGLE_THREAD_FETCH_SUCCESS",
  SINGLE_THREAD_FETCH_FAILURE = "SINGLE_THREAD_FETCH_FAILURE"
}
