export enum actionTypes {
  CATEGORIES_FETCH_REQUEST = "CATEGORIES_FETCH_REQUEST",
  CATEGORIES_FETCH_SUCCESS = "CATEGORIES_FETCH_SUCCESS",
  CATEGORIES_FETCH_FAILURE = "CATEGORIES_FETCH_FAILURE",

  THREADS_FETCH_REQUEST = "THREADS_FETCH_REQUEST",
  THREADS_FETCH_SUCCESS = "THREADS_FETCH_SUCCESS",
  THREADS_FETCH_FAILURE = "THREADS_FETCH_FAILURE"
}
